apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-clean-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-clean-app
  template:
    metadata:
      labels:
        app: gitops-clean-app
    spec:
      containers:
      - name: app
        image: ssimran602366879/gitops-clean-app:v1
        ports:
        - containerPort: 80
